### ISSUE TITLE
I realized my mistake.

### ISSUE THREAD

**Issue by zqvjhr1103** [planetarian/TsunKitTranslations#8]
I realized my mistake.

line317: 
×
"panelBonusesMaxLowModTip": "防御力の計算結果を最小防御力と想定した場合に考えられる最大の特効ボーナス\n防御力は装甲値×0.7 + 整数乱数(0 ～ (装甲値-1))×0.6で計算される。つまり最`大`防御力とは装甲値×0.7である。",

○
"panelBonusesMaxLowModTip": "防御力の計算結果を最小防御力と想定した場合に考えられる最大の特効ボーナス\n防御力は装甲値×0.7 + 整数乱数(0 ～ (装甲値-1))×0.6で計算される。つまり最`小`防御力とは装甲値×0.7である。",

I apologize.

**Comment by planetarian** [comment]
fixed in c884be7, thanks!
